apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatekeep-frontend
  labels:
    app: gatekeep-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gatekeep-frontend
  template:
    metadata:
      labels:
        app: gatekeep-frontend
    spec:
      containers:
        - name: frontend
          image: mangeshforstudy/gatekeep-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gatekeep-frontend-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: gatekeep-frontend
