apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name}}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name}}
  template:
    metatadata:
      labels:
        app: {{ .Values.backend.name}}
    spec:
      containers:
        - name: {{ .Values.backend.name}}
          image: {{ .Values.aws_repo_url}}/{{ .Values.backend.image}}:{{ .Values.backend.tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.containerPort}}
          env: 
            - name: PORT
              value: "{{ .Values.backend.containerPort}}"
            - name: DB_HOST
              value: {{ .Values.db.host}}
            - name: DB_PORT
              value: {{ .Values.db.port}}
            - name: DB_USER
              value: {{ .Values.db.user}}
            - name: DB_PASSWORD
              value: {{ .Values.db.password}}
            - name: DB_NAME
              value: {{ .Values.db.name}}
            - name: JWT_SECRET
              value: {{ .Values.jwt.secret}}
            - name: JWT_EXPIRES_IN
              value: {{ .Values.jwt.expiresIn}}
            