apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-aws-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 1h # Sync frequency
  secretStoreRef:
    name: aws-secret-manager-store
    kind: SecretStore
  target:
    name: myawssecrete-k8s # The Kubernetes Secret name to create
    creationPolicy: Owner
  data:
    - secretKey: aws_repo_url
      remoteRef:
        key: myawssecrete
        property: aws_repo_url
    - secretKey: host
      remoteRef:
        key: myawssecrete
        property: host
    - secretKey: password
      remoteRef:
        key: myawssecrete
        property: password
