name: Build and Push to Amazon ECR

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::570197775598:role/GitHubAction-ECR-Role
      - name: Test AWS Credentials
        run: aws sts get-caller-identity
